# Generated by Django 4.2.4 on 2023-08-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='product_categories',
        ),
        migrations.AddField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.DeleteModel(
            name='ProductsCategories',
        ),
    ]
